@startuml

title __SEEDERS's Class Diagram__\n

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.AudioRecordingSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.AvailableTimeSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.CourseSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.CoursesTutorsSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.DatabaseSeeder {
          ~ args : Object[]
          ~ context : Context
          + DatabaseSeeder()
          + displayData()
          + insertData()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.LocationSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.SchoolSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.StudentSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.TutorRatingSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.TutorSeeder {
          {static} + insert()
      }
    }
  }
  

  namespace com.jxust.tutor {
    namespace seeders {
      class com.jxust.tutor.seeders.TutoringSessionSeeder {
          {static} + insert()
      }
    }
  }
  

  com.jxust.tutor.seeders.DatabaseSeeder o-- com.jxust.tutor.models.DBHelper : mydb


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
